CREATE INDEX IF NOT EXISTS "agent_models_agent_id_idx" ON "agent_models" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_models_model_id_idx" ON "agent_models" USING btree ("model_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_tool_groups_agent_id_idx" ON "agent_tool_groups" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_tool_groups_tool_group_id_idx" ON "agent_tool_groups" USING btree ("tool_group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agents_creator_id_idx" ON "agents" USING btree ("creator_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agents_visibility_idx" ON "agents" USING btree ("visibility");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_user_id_idx" ON "Chat" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_agent_id_idx" ON "Chat" USING btree ("agentId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_created_at_idx" ON "Chat" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_user_id_idx" ON "Document" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_chat_id_idx" ON "Message" USING btree ("chatId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_model_id_idx" ON "Message" USING btree ("model_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_created_at_idx" ON "Message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "model_idx" ON "models" USING btree ("model");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "provider_idx" ON "models" USING btree ("provider");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "suggestion_document_id_idx" ON "Suggestion" USING btree ("documentId","documentCreatedAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "suggestion_user_id_idx" ON "Suggestion" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tool_group_tools_tool_group_id_idx" ON "tool_group_tools" USING btree ("tool_group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tool_group_tools_tool_id_idx" ON "tool_group_tools" USING btree ("tool_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tool_groups_creator_id_idx" ON "tool_groups" USING btree ("creator_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_email_idx" ON "User" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_transactions_user_id_idx" ON "user_transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_transactions_message_id_idx" ON "user_transactions" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_transactions_type_idx" ON "user_transactions" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_transactions_created_at_idx" ON "user_transactions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vote_chat_id_idx" ON "Vote" USING btree ("chatId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vote_message_id_idx" ON "Vote" USING btree ("messageId");